name: React build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
